Add code coverage and NuGet publishing to analyzer workflows

diff --git a/.github/workflows/analyzers_build_lint_test.yaml b/.github/workflows/analyzers_build_lint_test.yaml
--- a/.github/workflows/analyzers_build_lint_test.yaml
+++ b/.github/workflows/analyzers_build_lint_test.yaml
@@ -10,6 +10,7 @@ env:
   DOTNET_NOLOGO: 'true'
   DOTNET_VERSION: '9.0.x'
   BUILD_CONFIGURATION: 'Release'
+  NUGET_SOURCE_URL: https://pkgs.dev.azure.com/frends-platform/frends-tasks/_packaging/test/nuget/v3/index.json
 
 defaults:
   run:
@@ -71,6 +72,13 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
+      - name: Install xmlstarlet
+        env:
+          DEBIAN_FRONTEND: noninteractive
+        run: |
+          sudo apt update
+          sudo apt install --no-install-recommends -y xmlstarlet
+
       - name: Checkout
         uses: actions/checkout@v4.2.2
 
@@ -86,3 +94,54 @@ jobs:
 
       - name: Test
         run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --collect:"XPlat Code Coverage"
+
+      - id: code_coverage
+        name: Check code coverage
+        run: |
+          file=$(find . -name 'coverage.cobertura.xml' 2>/dev/null)
+          lineRate=$(xmlstarlet sel -t -v '//coverage/@line-rate' $file)
+          lineRatePct=$(printf "%.0f" $(echo "$lineRate * 100" | bc -l))
+          if [ $lineRatePct -lt 80 ]; then
+            echo "## Test coverage failed :x:" >> $GITHUB_STEP_SUMMARY
+            echo "**Line coverage:** $lineRatePct% | **Required:** 80%" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo "## Test coverage passed :white_check_mark:" >> $GITHUB_STEP_SUMMARY
+            echo "**Line coverage:** $lineRatePct%" >> $GITHUB_STEP_SUMMARY
+            echo "coverage=$lineRatePct" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Save coverage report
+        run: |
+          badgeKey="${{ github.repository }}/FrendsTaskAnalyzers|${{ github.ref_name }}"
+          json=$(jq -nc \
+            --arg key "$badgeKey" \
+            --arg displayName "Coverage" \
+            --arg value "${{ steps.code_coverage.outputs.coverage }}%" \
+            '{key: $key, displayName: $displayName, value: $value}')
+          curl \
+            -X POST \
+            -H "Content-Type: application/json" \
+            -H "x-api-key: ${{ secrets.badge_service_api_key }}" \
+            -d $json \
+            https://app-github-custom-badges.azurewebsites.net/Badge
+
+  push:
+    needs: test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: 'build'
+
+      - name: Setup .NET SDK
+        uses: actions/setup-dotnet@v4.3.1
+        with:
+          dotnet-version: ${{ env.DOTNET_VERSION }}
+
+      - name: Publish NuGet package
+        run: |
+          dotnet nuget push **/*.nupkg \
+            --api-key ${{ secrets.feed_api_key }} \
+            --source ${{ env.NUGET_SOURCE_URL }}
diff --git a/.github/workflows/analyzers_release.yaml b/.github/workflows/analyzers_release.yaml
--- a/.github/workflows/analyzers_release.yaml
+++ b/.github/workflows/analyzers_release.yaml
@@ -12,6 +12,7 @@ env:
   DOTNET_NOLOGO: 'true'
   DOTNET_VERSION: '9.0.x'
   BUILD_CONFIGURATION: 'Release'
+  NUGET_SOURCE_URL: https://pkgs.dev.azure.com/frends-platform/frends-tasks/_packaging/main/nuget/v3/index.json
 
 jobs:
   build:
@@ -23,6 +24,13 @@ jobs:
       run:
         working-directory: 'FrendsTaskAnalyzers/'
     steps:
+      - name: Install xmlstarlet
+        env:
+          DEBIAN_FRONTEND: noninteractive
+        run: |
+          sudo apt update
+          sudo apt install --no-install-recommends -y xmlstarlet
+
       - name: Checkout
         uses: actions/checkout@v4.2.2
         with:
@@ -31,14 +39,15 @@ jobs:
       - id: get-version
         name: Get project version
         run: |
-          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" FrendsTaskAnalyzers/FrendsTaskAnalyzers.csproj || echo "1.0.0")
+          VERSION=$(xmlstarlet sel -t -v "//Version" FrendsTaskAnalyzers/FrendsTaskAnalyzers.csproj 2>/dev/null || echo "1.0.0")
           echo "version=$VERSION" >> $GITHUB_OUTPUT
           echo "tag=v$VERSION" >> $GITHUB_OUTPUT
 
-      - name: Check if the tag exists
+      - name: Check if tag already exists
         run: |
           if git rev-parse "refs/tags/${{ steps.get-version.outputs.tag }}" >/dev/null 2>&1; then
-            echo "Duplicate tag found"
+            echo "## Release failed :x:" >> $GITHUB_STEP_SUMMARY
+            echo "Duplicate tag ${{ steps.get-version.outputs.tag }} already exists." >> $GITHUB_STEP_SUMMARY
             exit 1
           fi
 
@@ -76,7 +85,7 @@ jobs:
         with:
           name: 'release'
 
-      - name: Create Release
+      - name: Create release
         uses: softprops/action-gh-release@v2.2.2
         with:
           draft: false
@@ -87,3 +96,14 @@ jobs:
           name: FrendsTaskAnalyzers v${{ needs.build.outputs.version }}
           tag_name: ${{ needs.build.outputs.tag }}
           fail_on_unmatched_files: true
+
+      - name: Setup .NET SDK
+        uses: actions/setup-dotnet@v4.3.1
+        with:
+          dotnet-version: ${{ env.DOTNET_VERSION }}
+
+      - name: Publish NuGet package
+        run: |
+          dotnet nuget push **/*.nupkg \
+            --api-key ${{ secrets.feed_api_key }} \
+            --source ${{ env.NUGET_SOURCE_URL }}
