Cleanup GitHub Actions workflows

diff --git a/.github/workflows/build_main.yml b/.github/workflows/build_main.yml
--- a/.github/workflows/build_main.yml
+++ b/.github/workflows/build_main.yml
@@ -30,6 +30,7 @@ on:
       workdir:
         required: false
         type: string
+        default: '.'
       prebuild_command:
         required: false
         type: string
@@ -62,170 +63,162 @@ on:
       build_time_nuget_feed_api_key:
         required: false
 
-env:
-  workdir: ${{ inputs.workdir }}
+defaults:
+  run:
+    shell: pwsh
+    working-directory: ${{ inputs.workdir }}
 
 jobs:
   build:
     name: Build main branch
     runs-on: windows-latest
-    
+
     steps:
-    - uses: actions/checkout@v4.2.2
+      - name: Checkout
+        uses: actions/checkout@v4.2.2
 
-    ###############################
-    # SETUP DOTNET                #
-    ###############################
-    # When setting up dotnet, we need to check if a custom nuget feed is used
-    # However in GitHub Actions, in 'if' statements we cannot refer to 'secret' values, thus
-    # we need to use a small script to check if the secret is defined or not and then set an
-    # output to either true or false.
-    - name: Check for custom feed URL
-      id: check_for_build_time_feed
-      shell: pwsh
-      run: |
-        if ("${{ secrets.build_time_nuget_feed_url }}" -eq "")
-        { "Custom feed URL missing"; echo "build_time_nuget_feed_defined=false" >> $env:GITHUB_OUTPUT }
-        else 
-        { "Custom feed URL present"; echo "build_time_nuget_feed_defined=true" >> $env:GITHUB_OUTPUT }
+      ###############################
+      # SETUP DOTNET                #
+      ###############################
+      # When setting up dotnet, we need to check if a custom nuget feed is used
+      # However in GitHub Actions, in 'if' statements we cannot refer to 'secret' values, thus
+      # we need to use a small script to check if the secret is defined or not and then set an
+      # output to either true or false.
+      - id: check_build_time_feed
+        name: Check if custom NuGet feed is set
+        run: |
+          if ("${{ secrets.build_time_nuget_feed_url }}" -eq "")
+          {
+            echo "defined=false" >> $env:GITHUB_OUTPUT
+          }
+          else
+          {
+            echo "defined=true" >> $env:GITHUB_OUTPUT
+          }
 
-    - uses: actions/setup-dotnet@v4.3.1
-      name: Setup dotnet (no custom feed)
-      if: ${{ steps.check_for_build_time_feed.outputs.build_time_nuget_feed_defined == 'false' }}
-      with:
-        dotnet-version: ${{ inputs.dotnet_version }}
-    
-    # If a custom nuget feed is used, we need to add it when setting up dotnet
-    - uses: actions/setup-dotnet@v4.3.1
-      name: Setup dotnet (with custom feed)
-      if: ${{ steps.check_for_build_time_feed.outputs.build_time_nuget_feed_defined == 'true' }}
-      with:
-        dotnet-version: ${{ inputs.dotnet_version }}
-        source-url: ${{ secrets.build_time_nuget_feed_url }}
-      env:
-        NUGET_AUTH_TOKEN: ${{ secrets.build_time_nuget_feed_api_key }} 
+      - if: ${{ steps.check_build_time_feed.outputs.defined == 'false' }}
+        name: Setup .NET SDK
+        uses: actions/setup-dotnet@v4.3.1
+        with:
+          dotnet-version: ${{ inputs.dotnet_version }}
 
-    ###############################
-    # SETUP ENVIRONMENT IF NEEDED #
-    ###############################
-    - name: Set env var 1
-      if: ${{ inputs.env_var_name_1 != '' }}
-      run: |
-        echo "::add-mask::${{ secrets.env_var_value_1 }}"
-        echo "${{ inputs.env_var_name_1 }}=${{ secrets.env_var_value_1 }}" >> $env:GITHUB_ENV
-        
-    - name: Set env var 2
-      if: ${{ inputs.env_var_name_2 != '' }}
-      run: |
-        echo "::add-mask::${{ secrets.env_var_value_2 }}"
-        echo "${{ inputs.env_var_name_2 }}=${{ secrets.env_var_value_2 }}" >> $env:GITHUB_ENV
-        
-    - name: Set env var 3
-      if: ${{ inputs.env_var_name_3 != '' }}
-      run: |
-        echo "::add-mask::${{ secrets.env_var_value_3 }}"
-        echo "${{ inputs.env_var_name_3 }}=${{ secrets.env_var_value_3 }}" >> $env:GITHUB_ENV
-        
-    - name: Set env var 4
-      if: ${{ inputs.env_var_name_4 != '' }}
-      run: |
-        echo "::add-mask::${{ secrets.env_var_value_4 }}"
-        echo "${{ inputs.env_var_name_4 }}=${{ secrets.env_var_value_4 }}" >> $env:GITHUB_ENV
+      # If a custom nuget feed is used, we need to add it when setting up dotnet
+      - if: ${{ steps.check_build_time_feed.outputs.defined == 'true' }}
+        name: Setup .NET SDK (with custom feed)
+        uses: actions/setup-dotnet@v4.3.1
+        with:
+          dotnet-version: ${{ inputs.dotnet_version }}
+          source-url: ${{ secrets.build_time_nuget_feed_url }}
+        env:
+          NUGET_AUTH_TOKEN: ${{ secrets.build_time_nuget_feed_api_key }}
 
-    - name: Set env var 5
-      if: ${{ inputs.env_var_name_5 != '' }}
-      run: |
-        echo "::add-mask::${{ secrets.env_var_value_5 }}"
-        echo "${{ inputs.env_var_name_5 }}=${{ secrets.env_var_value_5 }}" >> $env:GITHUB_ENV
+      ###############################
+      # SETUP ENVIRONMENT IF NEEDED #
+      ###############################
+      - if: ${{ inputs.env_var_name_1 != '' }}
+        name: Set env var 1
+        run: |
+          echo "::add-mask::${{ secrets.env_var_value_1 }}"
+          echo "${{ inputs.env_var_name_1 }}=${{ secrets.env_var_value_1 }}" >> $env:GITHUB_ENV
 
-    - name: Set env var 6
-      if: ${{ inputs.env_var_name_6 != '' }}
-      run: |
-        echo "::add-mask::${{ secrets.env_var_value_6 }}"
-        echo "${{ inputs.env_var_name_6 }}=${{ secrets.env_var_value_6 }}" >> $env:GITHUB_ENV
+      - if: ${{ inputs.env_var_name_2 != '' }}
+        name: Set env var 2
+        run: |
+          echo "::add-mask::${{ secrets.env_var_value_2 }}"
+          echo "${{ inputs.env_var_name_2 }}=${{ secrets.env_var_value_2 }}" >> $env:GITHUB_ENV
 
-    - name: Set env var 7
-      if: ${{ inputs.env_var_name_7 != '' }}
-      run: |
-        echo "::add-mask::${{ secrets.env_var_value_7 }}"
-        echo "${{ inputs.env_var_name_7 }}=${{ secrets.env_var_value_7 }}" >> $env:GITHUB_ENV
+      - if: ${{ inputs.env_var_name_3 != '' }}
+        name: Set env var 3
+        run: |
+          echo "::add-mask::${{ secrets.env_var_value_3 }}"
+          echo "${{ inputs.env_var_name_3 }}=${{ secrets.env_var_value_3 }}" >> $env:GITHUB_ENV
 
-    - name: Set env var 8
-      if: ${{ inputs.env_var_name_8 != '' }}
-      run: |
-        echo "::add-mask::${{ secrets.env_var_value_8 }}"
-        echo "${{ inputs.env_var_name_8 }}=${{ secrets.env_var_value_8 }}" >> $env:GITHUB_ENV
+      - if: ${{ inputs.env_var_name_4 != '' }}
+        name: Set env var 4
+        run: |
+          echo "::add-mask::${{ secrets.env_var_value_4 }}"
+          echo "${{ inputs.env_var_name_4 }}=${{ secrets.env_var_value_4 }}" >> $env:GITHUB_ENV
 
-    - name: Set working directory if provided
-      if: ${{ inputs.workdir != '' }}
-      run: |
-        echo "workdir=${{ inputs.workdir }}" >> $env:GITHUB_ENV
+      - if: ${{ inputs.env_var_name_5 != '' }}
+        name: Set env var 5
+        run: |
+          echo "::add-mask::${{ secrets.env_var_value_5 }}"
+          echo "${{ inputs.env_var_name_5 }}=${{ secrets.env_var_value_5 }}" >> $env:GITHUB_ENV
 
-    - name: Set working directory to default if not provided
-      if: ${{ inputs.workdir == '' }}
-      run: |
-        echo "workdir=." >> $env:GITHUB_ENV
-        
-    ###############################
-    # Run prebuild command        #
-    ###############################
-    - name: Run prebuild command
-      if: ${{ inputs.prebuild_command != '' }}
-      run: ${{ inputs.prebuild_command }}
-      working-directory: "${{ env.workdir }}"
-      
-    ###############################
-    # Build, test, report results #
-    ###############################
-    - name: Build
-      run: dotnet build
-      working-directory: "${{ env.workdir }}"
-    
-    - name: Test
-      run: dotnet test --collect:"XPlat Code Coverage"
-      working-directory: "${{ env.workdir }}"
+      - if: ${{ inputs.env_var_name_6 != '' }}
+        name: Set env var 6
+        run: |
+          echo "::add-mask::${{ secrets.env_var_value_6 }}"
+          echo "${{ inputs.env_var_name_6 }}=${{ secrets.env_var_value_6 }}" >> $env:GITHUB_ENV
 
-    - name: Check Code Coverage
-      id: check_code_coverage
-      shell: pwsh
-      run: |
-        Get-ChildItem -Path "." -Include "coverage.cobertura.xml" -Recurse | Copy-Item -Destination .
-        [double] $coverage = ([xml]($tmp = Get-Content -Path 'coverage.cobertura.xml')).SelectSingleNode("/coverage/packages/package[@name='${{ env.workdir }}']").Attributes['line-rate'].Value
-        $coverageInt = [int]($coverage * 100)
-        if ($coverageInt -lt 80 ) 
-        {
-          echo "Test coverage $coverageInt % was not in the tolerance 80 %"
-          echo "The Code Check failed! :x:" >> $env:GITHUB_STEP_SUMMARY
-          echo "## Test coverage $coverageInt% was not in the tolerance 80% :thumbsdown:" >> $env:GITHUB_STEP_SUMMARY
-          exit 1
-        }
-        else 
-        {
-          echo "The Code Check passed :raised_hands:" >> $env:GITHUB_STEP_SUMMARY
-          echo "## Test coverage $coverageInt% :thumbsup:" >> $env:GITHUB_STEP_SUMMARY
-        }
-         
-    - name: Pack release version of task
-      run: dotnet pack --configuration Release --include-source
-      working-directory: "${{ env.workdir }}"
-      
-    - name: Save coverage results
-      id: vars
-      shell: pwsh
-      run: |
-        $badgeKey = "${{ github.repository }}|${{ github.ref_name }}"
-        $apiKey = "${{ secrets.badge_service_api_key }}"
-        if (!("${{ env.workdir }}" -eq '.')) {
-          $badgeKey = "${{ github.repository }}/${{ env.workdir }}|${{ github.ref_name }}"
-        }
-        Get-ChildItem -Path "." -Include "coverage.cobertura.xml" -Recurse | Copy-Item -Destination .
-        [double] $coverage = ([xml]($tmp = Get-Content -Path 'coverage.cobertura.xml')).SelectSingleNode("/coverage/packages/package[@name='${{ env.workdir }}']").Attributes['line-rate'].Value
-        $coverageInt = [int]($coverage * 100)
-        $json = @{key=$badgeKey;displayName='Coverage';value=[string]$coverageInt+"%"} | convertto-json
-        $headers = @{'x-api-key'=$apiKey}
-        $badgeKey
-        Invoke-WebRequest -Uri https://app-github-custom-badges.azurewebsites.net/Badge -Method POST -Body $json -Headers $headers -ContentType "application/json"
-      working-directory: "${{ env.workdir }}"
+      - if: ${{ inputs.env_var_name_7 != '' }}
+        name: Set env var 7
+        run: |
+          echo "::add-mask::${{ secrets.env_var_value_7 }}"
+          echo "${{ inputs.env_var_name_7 }}=${{ secrets.env_var_value_7 }}" >> $env:GITHUB_ENV
+
+      - if: ${{ inputs.env_var_name_8 != '' }}
+        name: Set env var 8
+        run: |
+          echo "::add-mask::${{ secrets.env_var_value_8 }}"
+          echo "${{ inputs.env_var_name_8 }}=${{ secrets.env_var_value_8 }}" >> $env:GITHUB_ENV
+
+      ###############################
+      # Run prebuild command        #
+      ###############################
+      - if: ${{ inputs.prebuild_command != '' }}
+        name: Run prebuild command
+        run: ${{ inputs.prebuild_command }}
+
+      ###############################
+      # Build, test, report results #
+      ###############################
+      - name: Build
+        run: dotnet build
+
+      - name: Test
+        run: dotnet test --collect:"XPlat Code Coverage"
+
+      - id: code_coverage
+        name: Check code coverage
+        run: |
+          $file = Get-ChildItem -Path . -Include 'coverage.cobertura.xml' -Recurse
+          $lineRate = [double](Select-Xml -XPath '//coverage/@line-rate' $file).Node.Value
+          $lineRatePct = [Math]::Round($lineRate * 100)
+          if ($lineRatePct -lt 80)
+          {
+            echo "## Test coverage failed :x:" >> $env:GITHUB_STEP_SUMMARY
+            echo "**Line coverage:** $lineRatePct% | **Required:** 80%" >> $env:GITHUB_STEP_SUMMARY
+            exit 1
+          }
+          else
+          {
+            echo "## Test coverage passed :white_check_mark:" >> $env:GITHUB_STEP_SUMMARY
+            echo "**Line coverage:** $lineRatePct%" >> $env:GITHUB_STEP_SUMMARY
+            echo "coverage=$lineRatePct" >> $GITHUB_OUTPUT
+          }
+
+      - name: Pack
+        run: dotnet pack --configuration Release --include-source
+
+      - name: Save coverage report
+        run: |
+          $badgeKey = "${{ github.repository }}|${{ github.ref_name }}"
+          if ("${{ inputs.workdir }}" -ne ".")
+          {
+            $badgeKey = "${{ github.repository }}/${{ inputs.workdir }}|${{ github.ref_name }}"
+          }
+          $json = @{
+            key = $badgeKey
+            displayName = "Coverage"
+            value = "${{ steps.code_coverage.outputs.lineRatePct }}%"
+          } | ConvertTo-Json -Compress
+          Invoke-WebRequest `
+              -Method POST `
+              -ContentType "application/json" `
+              -Headers @{ x-api-key = "${{ secrets.BADGE_SERVICE_API_KEY }}" } `
+              -Body $json `
+              https://app-github-custom-badges.azurewebsites.net/Badge
 
     ### WE ARE NOT PUSHING / CREATING RELEASE IMMEDIATELY ###
     ### USE release.yml TO CREATE THE RELEASE AND PUSH    ###
