refactor partner to use linux

diff --git a/.github/workflows/build_test_partner.yml b/.github/workflows/build_test_partner.yml
--- a/.github/workflows/build_test_partner.yml
+++ b/.github/workflows/build_test_partner.yml
@@ -32,7 +32,7 @@ env:
 jobs:
   CodeQualityCheck:
     name: Code quality check
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4.2.2
@@ -46,7 +46,7 @@ jobs:
   
   Build:
     name: Build non-main branch
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
 
     steps:
     - name: Checkout repository
@@ -64,6 +64,11 @@ jobs:
       run: |
         echo "workdir=${{ inputs.workdir }}" >> $env:GITHUB_ENV
 
+    - name: Install tools
+      run: |
+        sudo apt-get update
+        sudo apt-get install xmlstarlet -y
+
     - name: Run prebuild command
       if: ${{ inputs.prebuild_command != '' }}
       run: ${{ inputs.prebuild_command }}
@@ -78,24 +83,23 @@ jobs:
       working-directory: "${{ env.workdir }}"
 
     - name: Check Code Coverage
-      id: check_code_coverage
-      shell: pwsh
+      id: get_line_rate
       run: |
-        Get-ChildItem -Path "." -Include "coverage.cobertura.xml" -Recurse | Copy-Item -Destination .
-        [double] $coverage = ([xml]($tmp = Get-Content -Path 'coverage.cobertura.xml')).SelectSingleNode("/coverage/packages/package[@name='${{ env.workdir }}']").Attributes['line-rate'].Value
-        $coverageInt = [int]($coverage * 100)
-        if ($coverageInt -lt 80 ) 
-        {
-          echo "Test coverage $coverageInt % was not in the tolerance 80 %"
-          echo "The Code Check failed! :x:" >> $env:GITHUB_STEP_SUMMARY
-          echo "## Test coverage $coverageInt% was not in the tolerance 80% :thumbsdown:" >> $env:GITHUB_STEP_SUMMARY
+        report=$(find . -name "coverage.cobertura.xml" 2>/dev/null || true)
+        cp $report .
+        coverage=$(xmlstarlet sel -t -v '//coverage/@line-rate' coverage.cobertura.xml)
+        covPercent=$(echo "$coverage * 100" | bc -l)
+        coverageInt=$(printf "%.0f" $covPercent)
+        if test $coverageInt -lt 80 
+        then
+          echo "Test coverage $coverageInt% was not in the tolerance 80%"
+          echo "The Code Check failed! :x:" >> $GITHUB_STEP_SUMMARY
+          echo "## Test coverage $coverageInt% was not in the tolerance 80% :thumbsdown:" >> $GITHUB_STEP_SUMMARY
           exit 1
-        }
-        else 
-        {
-          echo "The Code Check passed :raised_hands:" >> $env:GITHUB_STEP_SUMMARY
-          echo "## Test coverage $coverageInt% :thumbsup:" >> $env:GITHUB_STEP_SUMMARY
-        }
+        else
+          echo "The Code Check passed :raised_hands:" >> $GITHUB_STEP_SUMMARY
+          echo "## Test coverage $coverageInt% :thumbsup:" >> $GITHUB_STEP_SUMMARY
+        fi
 
     - name: Pack release version of task
       run: dotnet pack -c Release
