Debugging sonar

diff --git a/.github/workflows/linux_build_test.yml b/.github/workflows/linux_build_test.yml
--- a/.github/workflows/linux_build_test.yml
+++ b/.github/workflows/linux_build_test.yml
@@ -83,35 +83,43 @@ jobs:
         FILTER_REGEX_INCLUDE: "${{ inputs.workdir }}/"
         
   sonarcloud:
-    name: SonarCloud
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
+    
     steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: recursive
-          fetch-depth: 0
-
-      - name: Install SonarCloud scanner
-        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
-        shell: powershell
-        # The --version argument is optional. If it is omitted the latest version will be installed.
-        run: |
-          New-Item -Path .\.sonar\scanner -ItemType Directory
-          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner --version 5.13.1
-
-      - name: Build
-        shell: powershell
-        env:
-          # Needed to get some information about the pull request, if any
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          # The secret referenced in the command-line by SONAR_TOKEN should be generated
-          # from https://sonarcloud.io/account/security/
-          # The organization and project arguments (see /o and /k) are displayed
-          # on the project dashboard in SonarCloud.
-        run: |
-          .\.sonar\scanner\dotnet-sonarscanner begin /k:"FrendsPlatform_Frends.SFTP" /o:"frendsplatform" /d:sonar.login="982223b88f873a0afc4c8f1bca5f554440d4e3cf" /d:sonar.host.url="https://sonarcloud.io"
-          dotnet build Frends.SFTP.WriteFile.sln
-          .\.sonar\scanner\dotnet-sonarscanner end /k:"FrendsPlatform_Frends.SFTP" /o:"frendsplatform" /d:sonar.login="982223b88f873a0afc4c8f1bca5f554440d4e3cf"
+    - name: Checkout repository
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0 # This is required for SonarCloud to compute the code differences
+    - name: Set up JDK 11
+      uses: actions/setup-java@v2
+      with:
+        java-version: 11 # SonarCloud recommends JDK 11 for its scanner
+    - name: Cache SonarCloud packages
+      uses: actions/cache@v2
+      with:
+        path: ~/.sonar/cache
+        key: ${{ runner.os }}-sonar
+        restore-keys: ${{ runner.os }}-sonar
+    - name: Build and analyze
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for integration
+        SONAR_TOKEN: 982223b88f873a0afc4c8f1bca5f554440d4e3cf    # Needed for authentication with SonarCloud
+      run: |
+        ./gradlew build # This is for Gradle. Use the relevant build command for your project.
+        ./gradlew sonarqube # This is for Gradle. Use the relevant Sonar command for your project.
+    - name: Check Quality Gate status
+      uses: highbyte/sonarscanner-action@v3
+      with:
+        args: >
+          -Dsonar.qualitygate.wait=true
+      env:
+        SONAR_TOKEN: 982223b88f873a0afc4c8f1bca5f554440d4e3cf
+    - name: Fail CI if Quality Gate fails
+      run: |
+        if [[ "${{ steps.sonarcloud.outcome }}" == "failure" ]]; then
+          echo "SonarCloud Quality Gate has failed. Check the report for more details."
+          exit 1
+        fi
 
   build:
     name: Build on ubuntu-latest
